#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

while read line; do
    # Skip comments
    if [ "${line:0:1}" == "#" ]; then
        continue
    fi
    if [ ${#line} -ge 72 ] || [ ${#line} -le 9 ]; then
        echo -e "\033[0;31mThe length of the message has to be between 9 and 72 characters."
        exit 1
    fi
done < "${1}"
